# Generated by Django 4.1.6 on 2023-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('MP', 'MP'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('IC', 'Ice-cream'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
