# Generated by Django 4.1.6 on 2023-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('MP', 'MP'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('IC', 'Ice-cream'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
